/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Report;

import Issue.ManageBorrow;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

import javax.swing.JFrame;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;

/**
 *
 * @author Soi Lan Tron
 */
public class TestReport extends javax.swing.JFrame {

    /**
     * Creates new form TestReport
     */
    public TestReport() {
        initComponents();
        this.setLocationRelativeTo(this);
        loadBookBorrow();
    }

    DefaultTableModel dtm;
    Connection conn;
    PreparedStatement pstmt;
    ResultSet rs;

    private void createTableBorrow() {
        dtm = new DefaultTableModel();
        dtm.addColumn("Student Id");
        dtm.addColumn("Call Number");
        dtm.addColumn("IssueDate");
        dtm.addColumn("DueDate");
        dtm.addColumn("IssueStatus");
        dtm.addColumn("Check out Date");

        jTable1.setModel(dtm);

    }

    private void loadBookBorrow() {
        try {
            //loai dang ki driver
            createTableBorrow();
            setConn();

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            // tao doi tuong ket noi
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost;database=LibDB", "sa", "123");
            // tao doi tuong thuc thi
            pstmt = conn.prepareStatement("SELECT * FROM dbo.StudentBook");
            //thuc thi doi tuong
            // luu ket qua vao doi tuong resultSet
            rs = pstmt.executeQuery();
            // lay recore tu resulset ra
            while (rs.next()) {
                // tao vector de luu tung recore
                Vector v = new Vector();
                // add revore vao dector
                v.add(0, rs.getString(1));
                v.add(1, rs.getString(2));
                v.add(2, rs.getString(3));
                v.add(3, rs.getString(4));
                v.add(4, rs.getString(5));
                v.add(5, rs.getString(6));

                // dua du lieu vao voi tham so ben trong la mot Vector
                dtm.addRow(v);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageBorrow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageBorrow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setConn() {
        try {
            //loai dang ki driver
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            // tao doi tuong ket noi
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost;database=LibDB", "sa", "123");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageBorrow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageBorrow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        btnReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        btnReport.setText("Print");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReport)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReport))
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        try {
            //loai dang ki driver
            createTableBorrow();
            setConn();

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            // tao doi tuong ket noi
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost;database=LibDB", "sa", "123");
            // tao doi tuong thuc thi
            pstmt = conn.prepareStatement("SELECT * FROM dbo.StudentBook WHERE StudentId LIKE '%" + jTextField1.getText() + "%'");
            //thuc thi doi tuong
            // luu ket qua vao doi tuong resultSet
            rs = pstmt.executeQuery();
            // lay recore tu resulset ra
            while (rs.next()) {
                // tao vector de luu tung recore
                Vector v = new Vector();
                // add revore vao dector
                v.add(0, rs.getString(1));
                v.add(1, rs.getString(2));
                v.add(2, rs.getString(3));
                v.add(3, rs.getString(4));
                v.add(4, rs.getString(5));
                v.add(5, rs.getString(6));

                // dua du lieu vao voi tham so ben trong la mot Vector
                dtm.addRow(v);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageBorrow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageBorrow.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed

        try {
            setConn();
            String sql = "SELECT * FROM StudentBook WHERE StudentId = '" + jTextField1.getText() + "' ";
            HashMap jparam = new HashMap();
            JasperDesign jdesign = JRXmlLoader.load("src\\Report\\report1.jrxml");

            JRDesignQuery jquery = new JRDesignQuery();
            jquery.setText(sql);
            jdesign.setQuery(jquery);
            JasperReport jreport;
            jreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(jreport, jparam, conn);
            //show print    
            net.sf.jasperreports.view.JRViewer jrview = new net.sf.jasperreports.view.JRViewer(jprint);
            JFrame jf = new JFrame("Report");
            jf.add(jrview);
            jf.setSize(900, 1000);
            jf.setLocationRelativeTo(null);
            jf.setVisible(true);
            jf.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        } catch (JRException ex) {
            Logger.getLogger(TestReport.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
